import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Container, CssBaseline, Hidden, ThemeProvider } from "@mui/material";
import { AppProps } from "next/app";
import theme from "@/styles/theme";
import Header from "@/shared/components/header";
import { SessionProvider } from "next-auth/react";
import Layout from "@/shared/layouts/layout";
import AuthGuard from "@/guards/authGuard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js | Session",
  description: "Generated by create next app",
} as const;

export default function MyApp({ Component, pageProps }: AppProps) {
  const { session } = pageProps;
  return (
    <>
      {/* <SessionProvider session={session}> */}

      <ThemeProvider theme={theme}>
        <Head>
          <title>{`${metadata.title}`}</title>
          <meta name="description" content={metadata.description || "N/A"} />
        </Head>
        <Header />
        <Container maxWidth="xl" style={{ paddingTop: 64, paddingBottom: 20 }}>

          {/* <AuthGuard> */}
          <Component {...pageProps} />
          {/* </AuthGuard> */}
          
        </Container>
      </ThemeProvider>

      {/* </SessionProvider> */}
    </>
  );
}
